name: "P4 Control Plane automation"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# workflow_dispatch:

concurrency:
  # If workflow for PR or push is already running, stop it and start a new one.
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  #---------------------------------------------------------------------
  # Environment variables
  #---------------------------------------------------------------------
  DEPS_PREFIX: p4-dev/x86-deps
  DEPS_ARTIFACT: stratum-deps
  DEPS_TARBALL: deps-ubuntu-20.04.tar.gz

  OVS_BUILD: ovs/build
  OVS_PREFIX: p4-dev/ovs
  OVS_ARTIFACT: p4cp-ovs
  OVS_TARBALL: ovs-ubuntu-20.04.tar.gz

  P4CP_PREFIX: p4-dev/p4cp-dpdk

  PREREQS: libbsd-dev libnl-3-dev libnl-route-3-dev libnl-genl-3-dev

jobs:
  #---------------------------------------------------------------------
  # 2-build_stratum_deps
  #---------------------------------------------------------------------
  build_stratum_deps:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone stratum-deps
        uses: actions/checkout@v3
        with:
          repository: ipdk-io/stratum-deps
          path: stratum-deps

      - name: Build stratum dependencies
        working-directory: stratum-deps
        run: |
          cmake --version
          export DEPEND_INSTALL=$GITHUB_WORKSPACE/$DEPS_PREFIX
          mkdir -pv $DEPEND_INSTALL
          cmake -B build -DCMAKE_INSTALL_PREFIX=$DEPEND_INSTALL -DGIT_PROGRESS=OFF
          cmake --build build -j6

      - name: Create stratum-deps tarball
        run: |
          tar -czf $DEPS_TARBALL $DEPS_PREFIX

      - name: Upload stratum-deps tarball
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.DEPS_ARTIFACT }}
          path: ${{ env.DEPS_TARBALL }}
          if-no-files-found: error

  #---------------------------------------------------------------------
  # 3-build_ovs
  #---------------------------------------------------------------------
  build_ovs:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone networking-recipe
        uses: actions/checkout@v3
        with:
          repository: ipdk-io/networking-recipe
          path: recipe

      - name: Initialize ovs submodule
        working-directory: recipe
        run: git submodule update --init --checkout --depth 1 ovs

      - name: Build OVS
        working-directory: recipe
        run: |
          export OVS_INSTALL=$GITHUB_WORKSPACE/$OVS_PREFIX
          mkdir -pv $OVS_INSTALL
          cmake -S ovs -B $OVS_BUILD -DCMAKE_INSTALL_PREFIX=$OVS_INSTALL -DP4OVS=ON
          cmake --build $OVS_BUILD -j6 -- V=0

      - name: Create ovs tarball
        run: tar -czf $OVS_TARBALL $OVS_PREFIX

      - name: Upload ovs tarball
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.OVS_ARTIFACT }}
          path: ${{ env.OVS_TARBALL }}
          if-no-files-found: error

  #---------------------------------------------------------------------
  # 4-build_dpdk_p4cp
  #---------------------------------------------------------------------
  build_dpdk_p4cp:
    runs-on: ubuntu-20.04
    needs: [build_stratum_deps, build_ovs]

    steps:
      - name: Download dpdk-sde-dev
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ffoulkes/p4-dev.dpdk-sde
          tag: 2023.10.1
          fileName: dpdk-sde-dev-ubuntu-20.04.tar.gz
          extract: true

      - name: Download stratum-deps tarball
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DEPS_ARTIFACT }}

      - name: Unpack stratum-deps tarball
        run: |
          tar xzf $DEPS_TARBALL
          rm -f $DEPS_TARBALL

      - name: Download ovs tarball
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.OVS_ARTIFACT }}

      - name: Unpack ovs tarball
        run: |
          tar xzf $OVS_TARBALL
          rm $OVS_TARBALL

      - name: Clone networking-recipe
        uses: actions/checkout@v3
        with:
          repository: ipdk-io/networking-recipe
          ref: dpdk-pkg-config-path
          submodules: recursive
          path: recipe

      - name: Install prerequisites
        run: |
          sudo apt install $PREREQS

      - name: Build P4CP for DPDK
        working-directory: recipe
        run: |
          export DEPEND_INSTALL=$GITHUB_WORKSPACE/$DEPS_PREFIX
          export OVS_INSTALL=$GITHUB_WORKSPACE/$OVS_PREFIX
          export SDE_INSTALL=$GITHUB_WORKSPACE/$SDE_PREFIX
          export P4CP_INSTALL=$GITHUB_WORKSPACE/$P4CP_PREFIX
          mkdir -pv $P4CP_INSTALL
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$P4CP_INSTALL -DSET_RPATH=ON -DTDI_TARGET=DPDK
          cmake --build build -j6 --target install

  #---------------------------------------------------------------------
  # 5-krnlmon_tests
  #---------------------------------------------------------------------
  krnlmon_tests:
    runs-on: ubuntu-20.04
    needs: build_stratum_deps

    steps:
      - name: Clone networking-recipe
        uses: actions/checkout@v3
        with:
          repository: ipdk-io/networking-recipe
          ref: dpdk-pkg-config-path
          path: recipe

      - name: Initialize krnlmon submodule
        working-directory: recipe
        run: git submodule update --init --checkout --depth 1 krnlmon
        
      - name: Download dpdk-sde-dev
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ffoulkes/p4-dev.dpdk-sde
          tag: 2023.10.1
          fileName: dpdk-sde-dev-ubuntu-20.04.tar.gz
          extract: true

      - name: Download stratum-deps tarball
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DEPS_ARTIFACT }}

      - name: Unpack stratum-deps tarball
        run: |
          tar xzf $DEPS_TARBALL
          rm -f $DEPS_TARBALL

      - name: Install prerequisites
        run: |
          sudo apt install $PREREQS

      - name: Run unit tests
        working-directory: recipe/krnlmon/krnlmon
        run: |
          export DEPEND_INSTALL=$GITHUB_WORKSPACE/$DEPS_PREFIX
          export SDE_INSTALL=$GITHUB_WORKSPACE/$SDE_PREFIX
          cmake -S . -B build -DTDI_TARGET=DPDK
          cmake --build build --target krnlmon-test
