name: "Kernel monitor unit test"

on:
  workflow_dispatch:
env:
  PREREQS: libbsd-dev libnl-3-dev libnl-route-3-dev libnl-genl-3-dev
  
jobs:
  unit_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone networking-recipe
        uses: actions/checkout@v3
        with:
          repository: ipdk-io/networking-recipe
          ref: dpdk-pkg-config-path
          path: recipe

      - name: Initialize krnlmon submodule
        working-directory: recipe
        run: git submodule update --init --checkout --depth 1 krnlmon

      - name: Install prerequisites
        run: |
          sudo apt install $PREREQS

      - name: Run unit tests
        working-directory: recipe/krnlmon/krnlmon
        run: |
          cmake -B build \
              -DDEPEND_INSTALL_DIR=/dev/null \
              -DSDE_INSTALL_DIR=/dev/null \
              -DSAI_SOURCE_DIR=$(realpath ../SAI) \
              -DCMAKE_MODULE_PATH=$(realpath ../../cmake) \
              -DTDI_TARGET=DPDK
          cmake --build build --target krnlmon-test
